ifndef TARGET
TARGET=openlab-fiteco-m3
endif

CONTIKI_SOURCEFILES += sensors.c

CONTIKI_PROJECT = openlab-sensors-collecting
all: $(CONTIKI_PROJECT)

CONTIKI = ../..
include $(CONTIKI)/Makefile.include

